server.port: 8083
spring:
  data:
    mongodb:
      username: teamteach
      password: DigiSherpa2021
      database: teamteach
      port: 27017
      host: main.digisherpa.ai
  rabbitmq:
    host: main.digisherpa.ai
    port: 5672
    virtual-host: teamteach
    username: admin
    password: DigiSherpa2021

app:
  security:
    jwt:
      authtype: Bearer
      expirationmins: 1440
      uri: asd
      header: jjh
    authentication:
      type: DBBASED
    key:
      keytype: shared
      signingsecret: fe80::6184:62f1:2b9e:5b8313:8666:1qaz

exchange:
  signup: signupexchange

gateway.url: "https://ms.digisherpa.ai"

signup.routingkeys: event.email
listen.queue.names: event.createjournal
