
micronaut:
  application:
    name: Journals
  server:
    port: 5000
---
micronaut:
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            validation:
              secret: pleaseChangeThisSecretForANewOne
      # writer:
      #   header:
      #     enabled: true
      # propagation:
      #   enabled: true
      #   service-id-regex: "offers-services"
---

mongodb:
  uri: "mongodb+srv://digisherpa:MongoSherpa21@digisherpa.h80qy.mongodb.net/digisherpa?retryWrites=true&w=majority"

---
eureka:
  client:
    enabled: true
    registration:
      enabled: true
      defaultZone: "${EUREKA_HOST:ms.digisherpa.ai}:${EUREKA_PORT:8761}"

